// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyjeuxatvtvrmhkjaopo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5amV1eGF0dnR2cm1oa2phb3BvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MDA4MDYsImV4cCI6MjA2MjA3NjgwNn0.ummKaogioHLTB-yh9dHfsJDClni1292sTe_xjO2nwIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);